name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint the source files
        run: yarn lint
      - name: Type check
        run: yarn type-check
      - name: Build the library
        run: yarn build
      - name: Build the typings
        run: yarn build:types
      - name: Execute the tests
        run: |
          yarn test:unit
          yarn test:functional
